CREATE TABLE jobs (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    molecule TEXT,
    match_score INT,
    mismatch INT,
    gap INT,
    nw_seq1_name TEXT,
    nw_seq2_name TEXT,
    nw_result TEXT,
    score INT,
    percent_id FLOAT,
    gaps INT,
    sw_seq1_name TEXT,
    sw_seq2_name TEXT,
    sw_result TEXT,
    score2 INT,
    percent_id2 FLOAT,
    gaps2 INT
);
